// Code generated by github.com/hasura/ndc-sdk-go/codegen, DO NOT EDIT.
package functions

import (
	"github.com/hasura/ndc-sdk-go/utils"
)

var functions_Decoder = utils.NewDecoder()

// FromValue decodes values from map
func (j *HelloArguments) FromValue(input map[string]any) error {
	var err error
	j.Count, err = utils.GetNullableInt[int](input, "count")
	if err != nil {
		return err
	}
	j.Greeting, err = utils.GetString(input, "greeting")
	if err != nil {
		return err
	}
	return nil
}

// ToMap encodes the struct to a value map
func (j CreateAuthorResult) ToMap() map[string]any {
	r := make(map[string]any)
	r["id"] = j.ID
	r["name"] = j.Name

	return r
}

// ToMap encodes the struct to a value map
func (j HelloResult) ToMap() map[string]any {
	r := make(map[string]any)
	r["count"] = j.Count
	r["reply"] = j.Reply

	return r
}
